apiVersion: apps/v1
kind: Deployment
metadata:
  name: somia-flower-app-deployment
  labels:
    app: example
spec: # Defines the Deployment Behaviour
  replicas: 3
  selector:
    matchLabels:
      app: somia
  template:
    metadata:
      labels:
        app: somia
    spec: # Define the Pod behaviour
      containers:
      - name: cart-app
        image: muralisocial123/flower-app:1.0
        resources:
          limits:
            memory: "250Mi"
            cpu: "100m"
          requests:
            memory: "128Mi"
            cpu: "50m"  
        ports:
        - containerPort: 3015
---
# Writing the service.yaml file to expose the application
apiVersion: v1
kind: Service
metadata:
  name: somia-flower-app-svc
spec:
  selector:
    app: somia
  ports:
  - port: 3016
    targetPort: 3015 
  type: LoadBalancer
        
